version: '3.9'
services:
  app:
    image: ghcr.io/algostract/unfiles:latest
    env_file:
      - .env
    volumes:
      - unfiles_data:/app/.data
      - unfiles_static:/app/static
    networks:
      - internal
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 2048M
        reservations:
          cpus: '0.4'
          memory: 1024M

volumes:
  unfiles_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/unfiles/.data
  unfiles_static:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/unfiles/static

networks:
  internal:
    driver: overlay
